# Header
menu:
  é¦–é¡µ: /
  å‹é“¾: /links
  å…³äº: /about

# ä¸»é¡µbannerå›¾
banner: /blogs/images/banner.jpeg

# ç«™ç‚¹é€šçŸ¥ä¿¡æ¯
notice: Hi there ğŸ‘‹ Welcome to my blog space,hope you hava a good day~

# ä½œè€…ä¿¡æ¯
author:
  name: KeyToLove
  avatar: https://s.gravatar.com/avatar/e2d21bed4d6ff8daa412b6d5576c4061?s=80
  description: Think twice code once

toc:
  max_depth: 3 # ç”Ÿæˆ TOC çš„æœ€å¤§æ·±åº¦
  min_depth: 2 # ç”Ÿæˆ TOC çš„æœ€å°æ·±åº¦

comments:
  enable: true
  use: 'valine' # valine || disqus
  # valine è¯„è®º
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # è¿™é‡ŒappIdå’ŒappKeyä¸€å®šä¸€å®šè¦æ”¹æˆè‡ªå·±çš„ï¼Œæ²¡æœ‰çš„è¯å»https://leancloud.cnè¿™ä¸ªç½‘ç«™æ³¨å†Œåˆ›å»ºä¸€ä¸ª
  valine:
    appId: epr01NN7HOiKlcWCvdv8swkK-gzGzoHsz
    appKey: tljBAMawJJHIlAT6oYAnGBz6
    avatar: mm
    placeholder: éšä¾¿è¯´ç‚¹ä»€ä¹ˆå­ï½
    notify: true
    visitor: true # ç»Ÿè®¡æµè§ˆé‡
    pageSize: 10
    enableQQ: true # æ˜¯å¦å¼€å¯æ˜µç§°è¾“å…¥æ¡†è‡ªåŠ¨è·å–QQæ˜µç§°å’Œå¤´åƒåŠŸèƒ½
    requiredFields: nick,mail
  # disqus è¯„è®º
  # docs: https://disqus.com/
  disqus:
    website:
    error: å¦‚æœä½ çœ‹ä¸åˆ°è¯„è®ºï¼Œé‚£ä¹ˆå°±çœŸçš„çœ‹ä¸åˆ°è¯„è®º w(ã‚œĞ”ã‚œ)w

# dplayer è§†é¢‘æ’­æ”¾
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: '#b7daff'
  autoplay: false
  loop: false
  mutex: true

# aplayer éŸ³é¢‘æ’­æ”¾
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: '#b7daff'
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# å›½å†…å¤‡æ¡ˆä¿¡æ¯
beian:

# è°·æ­Œåˆ†æ
google_analytics:
# gaugesåˆ†æ
gauges_analytics:
# ç™¾åº¦åˆ†æ
baidu_analytics:
# è…¾è®¯åˆ†æ
tencent_analytics:
# ç«™ç‚¹ico
favicon: /favicon.ico

# Social Icon
social_icon:
  enable: true
  icons:
    ins:
    zhihu:
    weibo:
    github: https://github.com/KeyToLove
    twitter:
